version: "3.8"
services:
  library-db:
    image: postgres
    container_name: library-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: library-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789