CREATE TABLE AUTHORS
(
    AUTHOR_ID   UUID PRIMARY KEY,
    AUTHOR_NAME VARCHAR(50)
);

CREATE TABLE BOOKS
(
    BOOK_ID           UUID PRIMARY KEY,
    BOOK_NAME         VARCHAR(50),
    BOOK_DESCRIPTION  VARCHAR(255),
    BOOK_RELEASE_YEAR INTEGER,
    BOOK_NUMBER_OF_PAGES INTEGER NOT NULL
);

CREATE TABLE BOOKS_AUTHORS
(
    BOOKS_AUTHORS_ID UUID PRIMARY KEY,
    AUTHOR_FK        INTEGER NOT NULL,
    BOOK_FK          INTEGER NOT NULL,
    FOREIGN KEY (AUTHOR_FK) REFERENCES AUTHORS (AUTHOR_ID),
    FOREIGN KEY (BOOK_FK) REFERENCES BOOKS (BOOK_ID)
);

INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('J.K. Rowling');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Stephen King');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Agatha Christie');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('George Orwell');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Harper Lee');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('J.R.R. Tolkien');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Jane Austen');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('F. Scott Fitzgerald');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Ernest Hemingway');
INSERT INTO AUTHORS (AUTHOR_NAME) VALUES ('Leo Tolstoy');

INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('Harry Potter and the Sorcerer''s Stone', 'A young wizard discovers his magical heritage', 1997, 320);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('The Shining', 'A family''s winter retreat becomes terrifyingly haunted', 1977, 512);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('Murder on the Orient Express', 'A classic murder mystery set on a train', 1934, 256);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('1984', 'A dystopian novel about surveillance and oppression', 1949, 328);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('To Kill a Mockingbird', 'A coming-of-age story set in the American South', 1960, 281);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('The Hobbit', 'An adventure in Middle-earth', 1937, 310);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('Pride and Prejudice', 'A romantic comedy of manners', 1813, 279);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('The Great Gatsby', 'A story of the Jazz Age and American Dream', 1925, 180);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('The Old Man and the Sea', 'A tale of a Cuban fisherman''s struggle', 1952, 127);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES) VALUES ('War and Peace', 'Epic novel set during the Napoleonic Wars', 1869, 1225);

INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (2, 2);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (3, 3);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (4, 4);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (5, 5);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (6, 6);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (7, 7);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (8, 8);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (9, 9);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (10, 10);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK) VALUES (9, 10);
