CREATE TABLE PEOPLE
(
    PERSON_ID          SERIAL PRIMARY KEY,
    PERSON_FIRST_NAME  VARCHAR(50),
    PERSON_MIDDLE_NAME VARCHAR(150),
    PERSON_LAST_NAME   VARCHAR(150),
    PERSON_USERNAME    VARCHAR(50),
    PERSON_BIRTH_DATE  DATE NOT NULL
);

CREATE TABLE CONTACT_TYPES
(
    CONTACT_TYPE_ID   SERIAL PRIMARY KEY,
    CONTACT_TYPE_NAME VARCHAR(50)
);

CREATE TABLE CONTACTS
(
    CONTACT_ID      SERIAL PRIMARY KEY,
    CONTACT_CONTENT VARCHAR(50),
    CONTACT_TYPE_FK INTEGER,
    PERSON_FK       INTEGER,
    FOREIGN KEY (PERSON_FK) REFERENCES PEOPLE (PERSON_ID),
    FOREIGN KEY (CONTACT_TYPE_FK) REFERENCES CONTACT_TYPES (CONTACT_TYPE_ID)
);

CREATE TABLE AUTHORS
(
    AUTHOR_ID   SERIAL PRIMARY KEY,
    AUTHOR_NAME VARCHAR(50)
);

CREATE TABLE BOOKS
(
    BOOK_ID              SERIAL PRIMARY KEY,
    BOOK_NAME            VARCHAR(50),
    BOOK_DESCRIPTION     VARCHAR(255),
    BOOK_RELEASE_YEAR    INTEGER,
    BOOK_NUMBER_OF_PAGES INTEGER NOT NULL
);

CREATE TABLE BOOKS_AUTHORS
(
    BOOKS_AUTHORS_ID SERIAL PRIMARY KEY,
    AUTHOR_FK        INTEGER NOT NULL,
    BOOK_FK          INTEGER NOT NULL,
    FOREIGN KEY (AUTHOR_FK) REFERENCES AUTHORS (AUTHOR_ID),
    FOREIGN KEY (BOOK_FK) REFERENCES BOOKS (BOOK_ID)
);

CREATE TABLE LOAN
(
    LOAN_ID          SERIAL PRIMARY KEY,
    LOAN_DATE        TIMESTAMP WITH TIME ZONE,
    LOAN_RETURN_DATE TIMESTAMP WITH TIME ZONE
);

INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('J.K. Rowling');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Stephen King');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Agatha Christie');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('George Orwell');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Harper Lee');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('J.R.R. Tolkien');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Jane Austen');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('F. Scott Fitzgerald');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Ernest Hemingway');
INSERT INTO AUTHORS (AUTHOR_NAME)
VALUES ('Leo Tolstoy');

INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('Harry Potter and the Sorcerer''s Stone', 'A young wizard discovers his magical heritage', 1997, 320);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('The Shining', 'A family''s winter retreat becomes terrifyingly haunted', 1977, 512);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('Murder on the Orient Express', 'A classic murder mystery set on a train', 1934, 256);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('1984', 'A dystopian novel about surveillance and oppression', 1949, 328);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('To Kill a Mockingbird', 'A coming-of-age story set in the American South', 1960, 281);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('The Hobbit', 'An adventure in Middle-earth', 1937, 310);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('Pride and Prejudice', 'A romantic comedy of manners', 1813, 279);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('The Great Gatsby', 'A story of the Jazz Age and American Dream', 1925, 180);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('The Old Man and the Sea', 'A tale of a Cuban fisherman''s struggle', 1952, 127);
INSERT INTO BOOKS (BOOK_NAME, BOOK_DESCRIPTION, BOOK_RELEASE_YEAR, BOOK_NUMBER_OF_PAGES)
VALUES ('War and Peace', 'Epic novel set during the Napoleonic Wars', 1869, 1225);

INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (2, 2);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (3, 3);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (4, 4);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (5, 5);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (6, 6);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (7, 7);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (8, 8);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (9, 9);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (10, 10);
INSERT INTO BOOKS_AUTHORS (AUTHOR_FK, BOOK_FK)
VALUES (9, 10);

INSERT INTO CONTACT_TYPES(CONTACT_TYPE_NAME)
VALUES ('E-mail'),
       ('Phone'),
       ('Whatsapp');

INSERT INTO PEOPLE (PERSON_FIRST_NAME, PERSON_MIDDLE_NAME, PERSON_LAST_NAME, PERSON_USERNAME, PERSON_BIRTH_DATE)
VALUES ('John', 'William', 'Doe', 'john.doe', '1990-05-15'),
       ('Jane', 'Elizabeth', 'Smith', 'jane.smith', '1985-08-20'),
       ('Michael', 'James', 'Johnson', 'michael.j', '1978-12-10'),
       ('Emily', 'Rose', 'Brown', 'emily.brown', '1995-03-25'),
       ('David', 'Robert', 'Jones', 'david.jones', '1980-09-05');


INSERT INTO CONTACTS(CONTACT_CONTENT, CONTACT_TYPE_FK, PERSON_FK)
VALUES ('john.doe@mail.com', 1, 1),
       ('555-555-5555', 2, 1),
       ('jane.smith', 1, 2),
       ('(123) 456-7890', 3, 3),
       ('michael.j', 1, 3),
       ('emily.brown', 1, 4),
       ('123-456-7890', 3, 4),
       ('david.jones', 1, 5);